begin;
select plan(30);
select has_table('public','study_subjects','subjects are reproducible');
select has_table('public','study_sessions','sessions are reproducible');
select has_table('public','study_goals','goals exist');
select has_table('public','study_notes','notes exist');
select col_is_not_null('public','study_subjects','user_id','subject ownership is required');
select col_is_not_null('public','study_sessions','user_id','session ownership is required');
select col_is_not_null('public','study_goals','user_id','goal ownership is required');
select col_is_not_null('public','study_notes','user_id','note ownership is required');
select has_index('public','study_subjects','study_subjects_owner_idx','subjects are owner indexed');
select has_index('public','study_sessions','study_sessions_owner_subject_idx','sessions are owner/subject indexed');
select has_index('public','study_goals','study_goals_owner_subject_idx','goals are owner/subject indexed');
select has_index('public','study_notes','study_notes_owner_subject_idx','notes are owner/subject indexed');
select is((select relrowsecurity from pg_catalog.pg_class where oid = 'public.study_subjects'::regclass), true, 'subjects enable RLS');
select is((select relrowsecurity from pg_catalog.pg_class where oid = 'public.study_sessions'::regclass), true, 'sessions enable RLS');
select is((select relrowsecurity from pg_catalog.pg_class where oid = 'public.study_goals'::regclass), true, 'goals enable RLS');
select is((select relrowsecurity from pg_catalog.pg_class where oid = 'public.study_notes'::regclass), true, 'notes enable RLS');
select policies_are('public','study_subjects',array['study_subjects_owner_all'],'subjects expose only the owner policy');
select policies_are('public','study_sessions',array['study_sessions_owner_all'],'sessions expose only the owner policy');
select policies_are('public','study_goals',array['study_goals_owner_all'],'goals expose only the owner policy');
select policies_are('public','study_notes',array['study_notes_owner_all'],'notes expose only the owner policy');
select has_constraint('public','study_subjects','study_subjects_user_id_fkey','subject owner has a foreign key');
select has_constraint('public','study_sessions','study_sessions_user_id_fkey','session owner has a foreign key');
select has_constraint('public','study_sessions','study_sessions_subject_id_fkey','session subject has a foreign key');
select has_constraint('public','study_goals','study_goals_user_id_fkey','goal owner has a foreign key');
select has_constraint('public','study_goals','study_goals_subject_id_fkey','goal subject has a foreign key');
select has_constraint('public','study_notes','study_notes_user_id_fkey','note owner has a foreign key');
select has_constraint('public','study_notes','study_notes_subject_id_fkey','note subject has a foreign key');
select has_trigger('public','study_sessions','enforce_study_subject_owner','session ownership is enforced');
select has_trigger('public','study_goals','enforce_study_subject_owner','goal ownership is enforced');
select has_trigger('public','study_notes','enforce_study_subject_owner','note ownership is enforced');
select * from finish();
rollback;
