import {
  Sparkles,
  FolderKanban,
  ListChecks,
  GraduationCap,
  LibraryBig,
  Wallet,
  PenLine,
  Languages,
  FileText,
  Bot,
  Settings,
  LayoutDashboard,
  Crown,
  Route,
  Swords,
  Users,
  PackageOpen,
  Clapperboard,
  Search,
  type LucideIcon,
} from "lucide-react";

export type NexoraModule = {
  id: string;
  label: string;
  path: string;
  icon: LucideIcon;
  description: string;
  group: "core" | "modules" | "system";
  category: "main" | "workspace" | "growth" | "intelligence" | "money" | "account";
  premium?: boolean;
  /** Whether this module is exposed to release-candidate testers. */
  releaseReady?: boolean;
};

export const MODULES: NexoraModule[] = [
  {
    id: "creator",
    releaseReady: true,
    label: "Creator Center",
    path: "/creator",
    icon: Clapperboard,
    description: "Plan, publish, and improve with real evidence",
    group: "modules",
    category: "growth",
  },
  {
    id: "journeys",
    releaseReady: true,
    label: "Journeys",
    path: "/journeys",
    icon: Route,
    description: "Daily missions and Momentum",
    group: "modules",
    category: "growth",
  },
  {
    id: "arena",
    releaseReady: true,
    label: "Arena",
    path: "/arena",
    icon: Swords,
    description: "Verified challenges",
    group: "modules",
    category: "growth",
  },
  {
    id: "community",
    releaseReady: true,
    label: "Community",
    path: "/community",
    icon: Users,
    description: "Private squads and verified activity",
    group: "modules",
    category: "growth",
  },
  {
    id: "packs",
    releaseReady: true,
    label: "Journey Packs",
    path: "/packs",
    icon: PackageOpen,
    description: "Server-built journey templates",
    group: "modules",
    category: "growth",
  },
  {
    id: "dashboard",
    releaseReady: true,
    label: "Dashboard",
    path: "/dashboard",
    icon: LayoutDashboard,
    description: "Your daily overview",
    group: "core",
    category: "main",
  },
  {
    id: "assistant",
    releaseReady: true,
    label: "Assistant",
    path: "/assistant",
    icon: Sparkles,
    description: "Talk to your AI",
    group: "core",
    category: "main",
  },
  {
    id: "search",
    releaseReady: true,
    label: "Search",
    path: "/search",
    icon: Search,
    description: "Search across your workspace",
    group: "core",
    category: "main",
  },
  {
    id: "projects",
    releaseReady: true,
    label: "Projects",
    path: "/projects",
    icon: FolderKanban,
    description: "Plan and ship your work",
    group: "modules",
    category: "workspace",
  },
  {
    id: "productivity",
    releaseReady: true,
    label: "Productivity",
    path: "/productivity",
    icon: ListChecks,
    description: "Tasks, focus, calendar",
    group: "modules",
    category: "workspace",
  },
  {
    id: "studio",
    label: "Studio",
    path: "/studio",
    icon: LibraryBig,
    description: "Daily learning and growth",
    group: "modules",
    category: "growth",
  },
  {
    id: "studies",
    releaseReady: true,
    label: "Studies",
    path: "/studies",
    icon: GraduationCap,
    description: "Learn faster with AI",
    group: "modules",
    category: "growth",
  },
  {
    id: "finance",
    label: "Finance",
    path: "/finance",
    icon: Wallet,
    description: "Track and plan money",
    group: "modules",
    category: "money",
  },
  {
    id: "content",
    label: "Content",
    path: "/content",
    icon: PenLine,
    description: "Write, edit, publish",
    group: "modules",
    category: "workspace",
  },
  {
    id: "translate",
    label: "Translate",
    path: "/translate",
    icon: Languages,
    description: "Multilingual, instant",
    group: "modules",
    category: "growth",
  },
  {
    id: "documents",
    label: "Documents",
    path: "/documents",
    icon: FileText,
    description: "Read, summarize, ask",
    group: "modules",
    category: "workspace",
  },
  {
    id: "agents",
    label: "Agents",
    path: "/agents",
    icon: Bot,
    description: "Custom AI agents",
    group: "modules",
    category: "intelligence",
    premium: true,
  },
  {
    id: "premium",
    releaseReady: true,
    label: "Premium",
    path: "/premium",
    icon: Crown,
    description: "Unlock everything",
    group: "system",
    category: "account",
  },
  {
    id: "settings",
    releaseReady: true,
    label: "Settings",
    path: "/settings",
    icon: Settings,
    description: "Preferences & account",
    group: "system",
    category: "account",
  },
];

/** Small allowlist used by the RC launcher; unfinished routes remain available for development. */
export const RELEASE_MODULES = MODULES.filter((module) => module.releaseReady);
