/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShellAgentsRouteImport } from './routes/_shell.agents'
import { Route as ShellAssistantRouteImport } from './routes/_shell.assistant'
import { Route as ShellContentRouteImport } from './routes/_shell.content'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellDocumentsRouteImport } from './routes/_shell.documents'
import { Route as ShellFinanceRouteImport } from './routes/_shell.finance'
import { Route as ShellPremiumRouteImport } from './routes/_shell.premium'
import { Route as ShellProductivityRouteImport } from './routes/_shell.productivity'
import { Route as ShellProjectsRouteImport } from './routes/_shell.projects'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellStudiesRouteImport } from './routes/_shell.studies'
import { Route as ShellTranslateRouteImport } from './routes/_shell.translate'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ShellAgentsAgentIdRouteImport } from './routes/_shell.agents.$agentId'
import { Route as ShellContentContentIdRouteImport } from './routes/_shell.content.$contentId'
import { Route as ShellDocumentsDocumentIdRouteImport } from './routes/_shell.documents.$documentId'
import { Route as ShellProjectsProjectIdRouteImport } from './routes/_shell.projects.$projectId'
import { Route as ShellStudiesSubjectIdRouteImport } from './routes/_shell.studies.$subjectId'
import { Route as ShellFinanceAccountsAccountIdRouteImport } from './routes/_shell.finance.accounts.$accountId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAgentsRoute = ShellAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAssistantRoute = ShellAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ShellRoute,
} as any)
const ShellContentRoute = ShellContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocumentsRoute = ShellDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFinanceRoute = ShellFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPremiumRoute = ShellPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProductivityRoute = ShellProductivityRouteImport.update({
  id: '/productivity',
  path: '/productivity',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsRoute = ShellProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStudiesRoute = ShellStudiesRouteImport.update({
  id: '/studies',
  path: '/studies',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTranslateRoute = ShellTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => ShellRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ShellAgentsAgentIdRoute = ShellAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => ShellAgentsRoute,
} as any)
const ShellContentContentIdRoute = ShellContentContentIdRouteImport.update({
  id: '/$contentId',
  path: '/$contentId',
  getParentRoute: () => ShellContentRoute,
} as any)
const ShellDocumentsDocumentIdRoute =
  ShellDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => ShellDocumentsRoute,
  } as any)
const ShellProjectsProjectIdRoute = ShellProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ShellProjectsRoute,
} as any)
const ShellStudiesSubjectIdRoute = ShellStudiesSubjectIdRouteImport.update({
  id: '/$subjectId',
  path: '/$subjectId',
  getParentRoute: () => ShellStudiesRoute,
} as any)
const ShellFinanceAccountsAccountIdRoute =
  ShellFinanceAccountsAccountIdRouteImport.update({
    id: '/accounts/$accountId',
    path: '/accounts/$accountId',
    getParentRoute: () => ShellFinanceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agents': typeof ShellAgentsRouteWithChildren
  '/assistant': typeof ShellAssistantRoute
  '/content': typeof ShellContentRouteWithChildren
  '/dashboard': typeof ShellDashboardRoute
  '/documents': typeof ShellDocumentsRouteWithChildren
  '/finance': typeof ShellFinanceRouteWithChildren
  '/premium': typeof ShellPremiumRoute
  '/productivity': typeof ShellProductivityRoute
  '/projects': typeof ShellProjectsRouteWithChildren
  '/settings': typeof ShellSettingsRoute
  '/studies': typeof ShellStudiesRouteWithChildren
  '/translate': typeof ShellTranslateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/agents/$agentId': typeof ShellAgentsAgentIdRoute
  '/content/$contentId': typeof ShellContentContentIdRoute
  '/documents/$documentId': typeof ShellDocumentsDocumentIdRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/studies/$subjectId': typeof ShellStudiesSubjectIdRoute
  '/finance/accounts/$accountId': typeof ShellFinanceAccountsAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agents': typeof ShellAgentsRouteWithChildren
  '/assistant': typeof ShellAssistantRoute
  '/content': typeof ShellContentRouteWithChildren
  '/dashboard': typeof ShellDashboardRoute
  '/documents': typeof ShellDocumentsRouteWithChildren
  '/finance': typeof ShellFinanceRouteWithChildren
  '/premium': typeof ShellPremiumRoute
  '/productivity': typeof ShellProductivityRoute
  '/projects': typeof ShellProjectsRouteWithChildren
  '/settings': typeof ShellSettingsRoute
  '/studies': typeof ShellStudiesRouteWithChildren
  '/translate': typeof ShellTranslateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/agents/$agentId': typeof ShellAgentsAgentIdRoute
  '/content/$contentId': typeof ShellContentContentIdRoute
  '/documents/$documentId': typeof ShellDocumentsDocumentIdRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/studies/$subjectId': typeof ShellStudiesSubjectIdRoute
  '/finance/accounts/$accountId': typeof ShellFinanceAccountsAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_shell/agents': typeof ShellAgentsRouteWithChildren
  '/_shell/assistant': typeof ShellAssistantRoute
  '/_shell/content': typeof ShellContentRouteWithChildren
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/documents': typeof ShellDocumentsRouteWithChildren
  '/_shell/finance': typeof ShellFinanceRouteWithChildren
  '/_shell/premium': typeof ShellPremiumRoute
  '/_shell/productivity': typeof ShellProductivityRoute
  '/_shell/projects': typeof ShellProjectsRouteWithChildren
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/studies': typeof ShellStudiesRouteWithChildren
  '/_shell/translate': typeof ShellTranslateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_shell/agents/$agentId': typeof ShellAgentsAgentIdRoute
  '/_shell/content/$contentId': typeof ShellContentContentIdRoute
  '/_shell/documents/$documentId': typeof ShellDocumentsDocumentIdRoute
  '/_shell/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/_shell/studies/$subjectId': typeof ShellStudiesSubjectIdRoute
  '/_shell/finance/accounts/$accountId': typeof ShellFinanceAccountsAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confirm-email'
    | '/onboarding'
    | '/reset-password'
    | '/sitemap.xml'
    | '/agents'
    | '/assistant'
    | '/content'
    | '/dashboard'
    | '/documents'
    | '/finance'
    | '/premium'
    | '/productivity'
    | '/projects'
    | '/settings'
    | '/studies'
    | '/translate'
    | '/auth/callback'
    | '/agents/$agentId'
    | '/content/$contentId'
    | '/documents/$documentId'
    | '/projects/$projectId'
    | '/studies/$subjectId'
    | '/finance/accounts/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confirm-email'
    | '/onboarding'
    | '/reset-password'
    | '/sitemap.xml'
    | '/agents'
    | '/assistant'
    | '/content'
    | '/dashboard'
    | '/documents'
    | '/finance'
    | '/premium'
    | '/productivity'
    | '/projects'
    | '/settings'
    | '/studies'
    | '/translate'
    | '/auth/callback'
    | '/agents/$agentId'
    | '/content/$contentId'
    | '/documents/$documentId'
    | '/projects/$projectId'
    | '/studies/$subjectId'
    | '/finance/accounts/$accountId'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/auth'
    | '/confirm-email'
    | '/onboarding'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_shell/agents'
    | '/_shell/assistant'
    | '/_shell/content'
    | '/_shell/dashboard'
    | '/_shell/documents'
    | '/_shell/finance'
    | '/_shell/premium'
    | '/_shell/productivity'
    | '/_shell/projects'
    | '/_shell/settings'
    | '/_shell/studies'
    | '/_shell/translate'
    | '/auth/callback'
    | '/_shell/agents/$agentId'
    | '/_shell/content/$contentId'
    | '/_shell/documents/$documentId'
    | '/_shell/projects/$projectId'
    | '/_shell/studies/$subjectId'
    | '/_shell/finance/accounts/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/agents': {
      id: '/_shell/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof ShellAgentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assistant': {
      id: '/_shell/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof ShellAssistantRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/content': {
      id: '/_shell/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ShellContentRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/documents': {
      id: '/_shell/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ShellDocumentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/finance': {
      id: '/_shell/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof ShellFinanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/premium': {
      id: '/_shell/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof ShellPremiumRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/productivity': {
      id: '/_shell/productivity'
      path: '/productivity'
      fullPath: '/productivity'
      preLoaderRoute: typeof ShellProductivityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects': {
      id: '/_shell/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ShellProjectsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/studies': {
      id: '/_shell/studies'
      path: '/studies'
      fullPath: '/studies'
      preLoaderRoute: typeof ShellStudiesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/translate': {
      id: '/_shell/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof ShellTranslateRouteImport
      parentRoute: typeof ShellRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_shell/agents/$agentId': {
      id: '/_shell/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof ShellAgentsAgentIdRouteImport
      parentRoute: typeof ShellAgentsRoute
    }
    '/_shell/content/$contentId': {
      id: '/_shell/content/$contentId'
      path: '/$contentId'
      fullPath: '/content/$contentId'
      preLoaderRoute: typeof ShellContentContentIdRouteImport
      parentRoute: typeof ShellContentRoute
    }
    '/_shell/documents/$documentId': {
      id: '/_shell/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof ShellDocumentsDocumentIdRouteImport
      parentRoute: typeof ShellDocumentsRoute
    }
    '/_shell/projects/$projectId': {
      id: '/_shell/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ShellProjectsProjectIdRouteImport
      parentRoute: typeof ShellProjectsRoute
    }
    '/_shell/studies/$subjectId': {
      id: '/_shell/studies/$subjectId'
      path: '/$subjectId'
      fullPath: '/studies/$subjectId'
      preLoaderRoute: typeof ShellStudiesSubjectIdRouteImport
      parentRoute: typeof ShellStudiesRoute
    }
    '/_shell/finance/accounts/$accountId': {
      id: '/_shell/finance/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/finance/accounts/$accountId'
      preLoaderRoute: typeof ShellFinanceAccountsAccountIdRouteImport
      parentRoute: typeof ShellFinanceRoute
    }
  }
}

interface ShellAgentsRouteChildren {
  ShellAgentsAgentIdRoute: typeof ShellAgentsAgentIdRoute
}

const ShellAgentsRouteChildren: ShellAgentsRouteChildren = {
  ShellAgentsAgentIdRoute: ShellAgentsAgentIdRoute,
}

const ShellAgentsRouteWithChildren = ShellAgentsRoute._addFileChildren(
  ShellAgentsRouteChildren,
)

interface ShellContentRouteChildren {
  ShellContentContentIdRoute: typeof ShellContentContentIdRoute
}

const ShellContentRouteChildren: ShellContentRouteChildren = {
  ShellContentContentIdRoute: ShellContentContentIdRoute,
}

const ShellContentRouteWithChildren = ShellContentRoute._addFileChildren(
  ShellContentRouteChildren,
)

interface ShellDocumentsRouteChildren {
  ShellDocumentsDocumentIdRoute: typeof ShellDocumentsDocumentIdRoute
}

const ShellDocumentsRouteChildren: ShellDocumentsRouteChildren = {
  ShellDocumentsDocumentIdRoute: ShellDocumentsDocumentIdRoute,
}

const ShellDocumentsRouteWithChildren = ShellDocumentsRoute._addFileChildren(
  ShellDocumentsRouteChildren,
)

interface ShellFinanceRouteChildren {
  ShellFinanceAccountsAccountIdRoute: typeof ShellFinanceAccountsAccountIdRoute
}

const ShellFinanceRouteChildren: ShellFinanceRouteChildren = {
  ShellFinanceAccountsAccountIdRoute: ShellFinanceAccountsAccountIdRoute,
}

const ShellFinanceRouteWithChildren = ShellFinanceRoute._addFileChildren(
  ShellFinanceRouteChildren,
)

interface ShellProjectsRouteChildren {
  ShellProjectsProjectIdRoute: typeof ShellProjectsProjectIdRoute
}

const ShellProjectsRouteChildren: ShellProjectsRouteChildren = {
  ShellProjectsProjectIdRoute: ShellProjectsProjectIdRoute,
}

const ShellProjectsRouteWithChildren = ShellProjectsRoute._addFileChildren(
  ShellProjectsRouteChildren,
)

interface ShellStudiesRouteChildren {
  ShellStudiesSubjectIdRoute: typeof ShellStudiesSubjectIdRoute
}

const ShellStudiesRouteChildren: ShellStudiesRouteChildren = {
  ShellStudiesSubjectIdRoute: ShellStudiesSubjectIdRoute,
}

const ShellStudiesRouteWithChildren = ShellStudiesRoute._addFileChildren(
  ShellStudiesRouteChildren,
)

interface ShellRouteChildren {
  ShellAgentsRoute: typeof ShellAgentsRouteWithChildren
  ShellAssistantRoute: typeof ShellAssistantRoute
  ShellContentRoute: typeof ShellContentRouteWithChildren
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDocumentsRoute: typeof ShellDocumentsRouteWithChildren
  ShellFinanceRoute: typeof ShellFinanceRouteWithChildren
  ShellPremiumRoute: typeof ShellPremiumRoute
  ShellProductivityRoute: typeof ShellProductivityRoute
  ShellProjectsRoute: typeof ShellProjectsRouteWithChildren
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellStudiesRoute: typeof ShellStudiesRouteWithChildren
  ShellTranslateRoute: typeof ShellTranslateRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAgentsRoute: ShellAgentsRouteWithChildren,
  ShellAssistantRoute: ShellAssistantRoute,
  ShellContentRoute: ShellContentRouteWithChildren,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDocumentsRoute: ShellDocumentsRouteWithChildren,
  ShellFinanceRoute: ShellFinanceRouteWithChildren,
  ShellPremiumRoute: ShellPremiumRoute,
  ShellProductivityRoute: ShellProductivityRoute,
  ShellProjectsRoute: ShellProjectsRouteWithChildren,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellStudiesRoute: ShellStudiesRouteWithChildren,
  ShellTranslateRoute: ShellTranslateRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ConfirmEmailRoute: ConfirmEmailRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
