-- NXR-037C: orchestration contract only. Heavy media work remains in the external worker.
alter table public.creator_projects add column source_path text, add column source_file_name text, add column source_content_type text, add column source_size_bytes bigint check(source_size_bytes is null or source_size_bytes>0), add column source_uploaded_at timestamptz, add column source_media jsonb;
alter table public.creator_jobs add column lease_owner text, add column lease_expires_at timestamptz, add column last_seen_at timestamptz, add column attempt_count integer not null default 0 check(attempt_count>=0), add column settings jsonb not null default '{}'::jsonb, add column cancellation_requested_at timestamptz, add column transcript_language text, add column processing_metadata jsonb;
alter table public.creator_clips add column aspect_ratio text check(aspect_ratio in ('9:16','1:1','16:9')), add column captions_enabled boolean not null default true, add column caption_style text not null default 'clean', add column render_version integer not null default 1 check(render_version>0), add column replaces_clip_id uuid references public.creator_clips(id);
create unique index creator_one_active_job_idx on public.creator_jobs(project_id) where status in ('queued','analyzing','transcribing','selecting_clips','rendering');
create index creator_jobs_claim_idx on public.creator_jobs(status,created_at) where status='queued';

create or replace function public.enqueue_creator_job(p_project_id uuid) returns uuid language plpgsql security definer set search_path=public,storage as $$
declare p public.creator_projects; result uuid;
begin
 if auth.uid() is null then raise exception using errcode='42501',message='AUTHENTICATION_REQUIRED'; end if;
 select * into p from public.creator_projects where id=p_project_id and user_id=auth.uid() for update;
 if not found then raise exception using errcode='42501',message='PROJECT_NOT_OWNED'; end if;
 if p.source_status<>'available' or p.source_path is null then raise exception using errcode='22023',message='SOURCE_NOT_READY'; end if;
 if p.source_path not like auth.uid()::text||'/'||p.id::text||'/source/%' then raise exception using errcode='22023',message='INVALID_SOURCE_PATH'; end if;
 if not exists(select 1 from storage.objects where bucket_id='creator-sources' and name=p.source_path and owner_id=auth.uid()::text) then raise exception using errcode='22023',message='SOURCE_OBJECT_MISSING'; end if;
 if exists(select 1 from public.creator_jobs where project_id=p.id and status in ('queued','analyzing','transcribing','selecting_clips','rendering')) then raise exception using errcode='23505',message='ACTIVE_JOB_EXISTS'; end if;
 insert into public.creator_jobs(project_id,user_id,status,progress_stage,settings) values(p.id,p.user_id,'queued','queued',jsonb_build_object('aspect_ratio',p.aspect_ratio,'target_duration_seconds',p.target_duration_seconds,'captions_enabled',p.captions_enabled,'caption_style','clean')) returning id into result;
 update public.creator_projects set status='processing',updated_at=now() where id=p.id; return result;
end$$;
revoke all on function public.enqueue_creator_job(uuid) from public; grant execute on function public.enqueue_creator_job(uuid) to authenticated;

create or replace function public.creator_claim_job(p_lease_owner text,p_lease_seconds integer default 120,p_max_attempts integer default 3) returns table(id uuid,project_id uuid,user_id uuid,source_path text,aspect_ratio text,target_duration_seconds smallint,captions_enabled boolean,settings jsonb) language plpgsql security definer set search_path=public as $$
begin return query with next as (select j.id from creator_jobs j where (j.status='queued' or (j.status in ('analyzing','transcribing','selecting_clips','rendering') and j.lease_expires_at<now())) and j.attempt_count<p_max_attempts and j.cancellation_requested_at is null order by j.created_at for update skip locked limit 1), claimed as (update creator_jobs j set status='analyzing',progress_stage='analyzing',lease_owner=p_lease_owner,lease_expires_at=now()+make_interval(secs=>greatest(30,p_lease_seconds)),last_seen_at=now(),attempt_count=attempt_count+1,started_at=coalesce(started_at,now()) from next where j.id=next.id returning j.*) select c.id,c.project_id,c.user_id,p.source_path,(c.settings->>'aspect_ratio'),(c.settings->>'target_duration_seconds')::smallint,(c.settings->>'captions_enabled')::boolean,c.settings from claimed c join creator_projects p on p.id=c.project_id; end$$;
revoke all on function public.creator_claim_job(text,integer,integer) from public;
create or replace function public.creator_heartbeat(p_job_id uuid,p_lease_owner text,p_lease_seconds integer) returns boolean language sql security definer set search_path=public as $$update creator_jobs set last_seen_at=now(),lease_expires_at=now()+make_interval(secs=>greatest(30,p_lease_seconds)) where id=p_job_id and lease_owner=p_lease_owner and status in ('analyzing','transcribing','selecting_clips','rendering') returning true$$;
create or replace function public.creator_worker_stage(p_job_id uuid,p_lease_owner text,p_status creator_job_status) returns boolean language plpgsql security definer set search_path=public as $$begin if p_status not in ('analyzing','transcribing','selecting_clips','rendering') then raise exception 'INVALID_STAGE';end if;update creator_jobs set status=p_status,progress_stage=p_status,last_seen_at=now() where id=p_job_id and lease_owner=p_lease_owner and lease_expires_at>now();return found;end$$;
create or replace function public.creator_worker_cancel_requested(p_job_id uuid,p_lease_owner text) returns boolean language sql security definer set search_path=public as $$select cancellation_requested_at is not null from creator_jobs where id=p_job_id and lease_owner=p_lease_owner$$;
create or replace function public.cancel_creator_job(p_job_id uuid) returns boolean language plpgsql security definer set search_path=public as $$begin update creator_jobs set cancellation_requested_at=now(),status=case when status='queued' then 'cancelled' else status end,completed_at=case when status='queued' then now() else completed_at end where id=p_job_id and user_id=auth.uid() and status in ('queued','analyzing','transcribing','selecting_clips','rendering');return found;end$$;
grant execute on function public.cancel_creator_job(uuid) to authenticated;
create or replace function public.creator_worker_complete(p_job_id uuid,p_lease_owner text,p_media jsonb,p_transcript_language text,p_clip_count integer) returns boolean language plpgsql security definer set search_path=public as $$declare pid uuid;begin if p_clip_count<1 or not exists(select 1 from creator_clips where job_id=p_job_id and render_status='available' and output_path is not null) then raise exception 'RESULTS_NOT_READY';end if;update creator_jobs set status='completed',progress_stage='completed',completed_at=now(),processing_metadata=p_media,transcript_language=p_transcript_language,lease_owner=null,lease_expires_at=null where id=p_job_id and lease_owner=p_lease_owner returning project_id into pid;if pid is null then return false;end if;update creator_projects set status='completed',source_media=p_media,updated_at=now() where id=pid;return true;end$$;
create or replace function public.creator_worker_fail(p_job_id uuid,p_lease_owner text,p_error_code text,p_retryable boolean,p_max_attempts integer) returns boolean language plpgsql security definer set search_path=public as $$declare pid uuid;begin update creator_jobs set status=case when cancellation_requested_at is not null or p_error_code='CANCELLED' then 'cancelled' when p_retryable and attempt_count<p_max_attempts then 'queued' else 'failed' end,progress_stage=case when p_retryable and attempt_count<p_max_attempts then 'queued' else 'failed' end,error_code=left(p_error_code,80),completed_at=case when p_retryable and attempt_count<p_max_attempts then null else now() end,lease_owner=null,lease_expires_at=null where id=p_job_id and lease_owner=p_lease_owner returning project_id into pid;if pid is not null and exists(select 1 from creator_jobs where id=p_job_id and status in ('failed','cancelled')) then update creator_projects set status=(select status::text::creator_project_status from creator_jobs where id=p_job_id),updated_at=now() where id=pid;end if;return pid is not null;end$$;
revoke all on function public.creator_heartbeat(uuid,text,integer),public.creator_worker_stage(uuid,text,creator_job_status),public.creator_worker_cancel_requested(uuid,text),public.creator_worker_complete(uuid,text,jsonb,text,integer),public.creator_worker_fail(uuid,text,text,boolean,integer) from public;

create or replace function public.enqueue_creator_rerender(p_clip_id uuid,p_start_ms bigint,p_end_ms bigint,p_aspect_ratio text,p_captions boolean,p_caption_style text default 'clean') returns uuid language plpgsql security definer set search_path=public as $$declare c creator_clips;result uuid;begin select * into c from creator_clips where id=p_clip_id and user_id=auth.uid() and render_status='available';if not found then raise exception 'CLIP_NOT_AVAILABLE';end if;if p_start_ms<0 or p_end_ms<=p_start_ms or p_end_ms-p_start_ms>60000 or p_aspect_ratio not in ('9:16','1:1','16:9') or p_caption_style<>'clean' then raise exception 'INVALID_RENDER_SETTINGS';end if;insert into creator_jobs(project_id,user_id,status,progress_stage,settings) values(c.project_id,c.user_id,'queued','queued',jsonb_build_object('rerender_clip_id',c.id,'start_ms',p_start_ms,'end_ms',p_end_ms,'aspect_ratio',p_aspect_ratio,'captions_enabled',p_captions,'caption_style',p_caption_style)) returning id into result;return result;end$$;grant execute on function public.enqueue_creator_rerender(uuid,bigint,bigint,text,boolean,text) to authenticated;
