-- Journeys 2D: make completion, Momentum and challenge progress server-authoritative.
-- No domain constraint introduced by Journeys Foundation is NOT VALID. The legacy
-- Studies foreign keys remain intentionally unvalidated until staging audits the
-- pre-existing rows (see docs/journeys-momentum-challenges-hardening.md).

alter table public.journeys enable row level security;
alter table public.journey_missions enable row level security;
alter table public.momentum_events enable row level security;
alter table public.challenges enable row level security;
alter table public.user_challenges enable row level security;

-- Missions are generated by trusted functions and completion is applied by verified
-- source triggers/RPCs. Owners retain read access, but no direct mutation surface.
drop policy if exists "owners update mission state" on public.journey_missions;

-- Explicitly document/reinforce the critical-table grants. RLS remains the second
-- boundary for reads; authenticated clients cannot manufacture event/progress rows.
revoke insert, update, delete on public.journey_missions from authenticated;
revoke insert, update, delete on public.momentum_events from authenticated;
revoke insert, update, delete on public.challenges from authenticated;
revoke insert, update, delete on public.user_challenges from authenticated;

create or replace function public.apply_verified_mission_effects(p_mission public.journey_missions)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  inserted_event uuid;
  participation record;
begin
  -- The unique key (owner, mission, event type) is the idempotency boundary.
  insert into public.momentum_events(
    user_id, journey_id, source_type, source_id, event_type, points
  ) values (
    p_mission.user_id, p_mission.journey_id, 'mission', p_mission.id,
    'mission_completed', p_mission.momentum_value
  )
  on conflict (user_id, source_type, source_id, event_type) do nothing
  returning id into inserted_event;

  -- A replay that did not create the verified event cannot advance a challenge.
  if inserted_event is null then return; end if;

  for participation in
    insert into public.user_challenges(user_id, challenge_id, progress)
    select p_mission.user_id, c.id, 1
    from public.challenges c
    where c.active
      and c.type = 'mission_completions'
      and statement_timestamp() >= c.starts_at
      and statement_timestamp() < c.ends_at
    on conflict (user_id, challenge_id) do update
      set progress = least(
        public.user_challenges.progress + 1,
        (select c2.target_value from public.challenges c2 where c2.id = excluded.challenge_id)
      )
    returning challenge_id, progress
  loop
    update public.user_challenges uc
    set completed_at = coalesce(uc.completed_at, statement_timestamp())
    from public.challenges c
    where uc.user_id = p_mission.user_id
      and uc.challenge_id = participation.challenge_id
      and c.id = uc.challenge_id
      and uc.progress >= c.target_value;

    insert into public.momentum_events(
      user_id, source_type, source_id, event_type, points
    )
    select uc.user_id, 'challenge', uc.challenge_id,
      'weekly_challenge_completed', c.reward_points
    from public.user_challenges uc
    join public.challenges c on c.id = uc.challenge_id
    where uc.user_id = p_mission.user_id
      and uc.challenge_id = participation.challenge_id
      and uc.completed_at is not null
    on conflict (user_id, source_type, source_id, event_type) do nothing;
  end loop;
end
$$;
revoke all on function public.apply_verified_mission_effects(public.journey_missions) from public;
revoke all on function public.apply_verified_mission_effects(public.journey_missions) from authenticated;

create or replace function public.complete_verified_missions()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  mission public.journey_missions;
  verified_source_type text;
  verified_source_id uuid;
begin
  if tg_table_name = 'tasks' then
    verified_source_type := 'task';
    verified_source_id := new.id;
  elsif tg_table_name = 'study_sessions' then
    -- Daily Study missions point at the subject, not an individual session.
    verified_source_type := 'study_session';
    verified_source_id := new.subject_id;
  else
    raise exception 'unsupported_mission_source';
  end if;

  for mission in
    update public.journey_missions
    set status = 'completed', completed_at = statement_timestamp(),
      updated_at = statement_timestamp()
    where user_id = new.user_id
      and source_type = verified_source_type
      and source_id = verified_source_id
      and status in ('pending', 'active')
    returning *
  loop
    perform public.apply_verified_mission_effects(mission);
  end loop;
  return new;
end
$$;
revoke all on function public.complete_verified_missions() from public;
revoke all on function public.complete_verified_missions() from authenticated;

-- Repair the mismatched historical Studies trigger (it referenced a non-contract
-- status column and session id). Inserts are relevant because sessions default to
-- completed; updates cover explicitly pending sessions becoming complete.
drop trigger if exists studies_verify_missions on public.study_sessions;
drop trigger if exists studies_verify_missions_insert on public.study_sessions;
create trigger studies_verify_missions_insert
after insert on public.study_sessions
for each row when (new.completed = true)
execute function public.complete_verified_missions();
create trigger studies_verify_missions
after update of completed on public.study_sessions
for each row when (new.completed = true and old.completed is distinct from true)
execute function public.complete_verified_missions();

create or replace function public.complete_journey_action(p_mission uuid)
returns public.journey_missions
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  uid uuid := auth.uid();
  result public.journey_missions;
begin
  if uid is null then raise exception 'authentication_required'; end if;

  select m.* into result
  from public.journey_missions m
  join public.journeys j on j.id = m.journey_id
  where m.id = p_mission
    and m.user_id = uid
    and j.user_id = uid
    and m.source_type = 'journey_action'
  for update of m;

  if result.id is null then raise exception 'mission_not_confirmable'; end if;
  if result.status = 'completed' then return result; end if;
  if result.status not in ('pending', 'active') then raise exception 'mission_not_confirmable'; end if;

  update public.journey_missions
  set status = 'completed', completed_at = statement_timestamp(),
    updated_at = statement_timestamp()
  where id = result.id
  returning * into result;

  perform public.apply_verified_mission_effects(result);
  return result;
end
$$;
revoke all on function public.complete_journey_action(uuid) from public;
grant execute on function public.complete_journey_action(uuid) to authenticated;

-- The daily date is supplied for the user's local calendar, but must remain close
-- to server time so it cannot be used to pre-generate arbitrary historical rows.
create or replace function public.ensure_daily_journey_mission(p_local_date date)
returns public.journey_missions
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  uid uuid := auth.uid();
  found public.journey_missions;
  candidate record;
begin
  if uid is null then raise exception 'authentication_required'; end if;
  if p_local_date is null or p_local_date < current_date - 1 or p_local_date > current_date + 1 then
    raise exception 'invalid_mission_date';
  end if;
  select * into found from public.journey_missions where user_id=uid and scheduled_date=p_local_date;
  if found.id is not null then return found; end if;
  perform pg_advisory_xact_lock(hashtextextended(uid::text||p_local_date::text,0));
  select * into found from public.journey_missions where user_id=uid and scheduled_date=p_local_date;
  if found.id is not null then return found; end if;
  select 'task'::text source_type,t.id source_id,t.title,coalesce(t.next_action,t.description) description,
    case when t.due_date<p_local_date then 0 when t.due_date=p_local_date then 10 when t.next_action is not null then 20 when t.due_date is not null then 40 else 60 end rank
  into candidate from public.tasks t left join public.projects p on p.id=t.project_id
  where t.user_id=uid and not t.completed and (t.project_id is null or p.status='active')
  order by rank,t.title,t.id limit 1;
  if candidate.source_id is null then
    select 'study_session'::text,s.id,('Estudar '||s.name),s.next_action,30 into candidate
    from public.study_subjects s where s.user_id=uid and s.status='active'
      and nullif(btrim(s.next_action),'') is not null order by s.updated_at desc,s.id limit 1;
  end if;
  if candidate.source_id is null then return null; end if;
  insert into public.journey_missions(user_id,source_type,source_id,title,description,status,scheduled_date)
  values(uid,candidate.source_type,candidate.source_id,candidate.title,candidate.description,'active',p_local_date)
  returning * into found;
  return found;
end
$$;
revoke all on function public.ensure_daily_journey_mission(date) from public;
grant execute on function public.ensure_daily_journey_mission(date) to authenticated;
